# Generated by Django 6.0.8 on 2026-09-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(help_text='Short summary shown on the card.')),
                ('image', models.ImageField(blank=True, help_text='Upload a thumbnail. Falls back to the static image below.', null=True, upload_to='projects/')),
                ('static_image', models.CharField(blank=True, help_text='Fallback path under static/ (e.g. images/bix-home.png).', max_length=255)),
                ('link', models.URLField(help_text="External URL opened by 'view project'.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.ImageField(blank=True, help_text='Upload an icon. Falls back to the static icon below.', null=True, upload_to='skills/')),
                ('static_icon', models.CharField(blank=True, help_text='Fallback path under static/ (e.g. assets/images/icons/php.png).', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'id'],
            },
        ),
    ]
