# Generated by Django 6.0.8 on 2026-10-01 09:23

import django.core.validators
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default='Hi, my name is Princewill', help_text='Small line above the headline.', max_length=150)),
                ('headline', models.CharField(default='I build solutions for the web.', help_text='Main tagline shown as the page heading.', max_length=200)),
                ('description', models.TextField(help_text='Intro paragraph. Supports bold, links and lists.')),
                ('contact_heading', models.CharField(default='Get in touch', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a photo. Falls back to the static image below.', null=True, upload_to='profile/')),
                ('static_image', models.CharField(blank=True, help_text='Fallback path under static/ (e.g. images/user_icon.jpg).', max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, default='princewilldev.com', max_length=120)),
                ('resume_file', models.FileField(blank=True, help_text='PDF, DOC or DOCX (max 10 MB). Upload a new file to replace.', null=True, upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), portfolio.validators.validate_cv_size])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
