# Generated by Django 6.0.8 on 2026-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_seed_siteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Full project details shown on the project page. Supports rich text: headings, bold, links, lists, images and code.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Brief summary shown on the home page card.'),
        ),
    ]
